### ISSUE TITLE
宮内やることリスト1

### ISSUE THREAD

**Issue by kynmh69** [YU01BLC/w-sns#2]
# Github

- [x] githubのslack連携
- [x] githubのProject作成
- [x] #1 か、別のブランチにNextのプロジェクトの初期構築を行う
- [x] Wikiの有効化
- [x] Discussionの有効化

## プロジェクト作成について

1. Projectsタブ→プルダウンからNew Projectを選択

<img width="1303" alt="Screenshot 2024-02-16 at 7 39 09 PM" src="https://github.com/YU01BLC/w-sns/assets/32707877/b271cc57-081f-45d8-8694-17117e4e5fc8">

2. Team Planningを選択してCreate Project（プロジェクト名は適当で）

<img width="977" alt="Screenshot 2024-02-16 at 7 42 33 PM" src="https://github.com/YU01BLC/w-sns/assets/32707877/acdb4dc7-7834-4aa3-93a3-73914efe4aaf">

これで行けるはず（？）

## Wikiの有効化とdiscussionの有効化について

1. settingsタブを選択

<img width="905" alt="image" src="https://github.com/YU01BLC/w-sns/assets/32707877/7b2a432a-81da-46e2-a4fb-dc805fcba31d">

2. WikisとDisscussionにチェックを入れる

Featuresまでスクロールする。

<img width="806" alt="image" src="https://github.com/YU01BLC/w-sns/assets/32707877/6be00482-ac27-44ae-8a78-f7a447e59ee4">

**Comment by YU01BLC** [comment]
遅くなってすまんmm
確認お願いしますー @kynmh69 

プロジェクト作成
- https://github.com/users/YU01BLC/projects/1/views/1

Discussionの有効化
- https://github.com/YU01BLC/w-sns/discussions/19

**Comment by kynmh69** [comment]
> プロジェクト作成
> 
> * https://github.com/users/YU01BLC/projects/1/views/1

プロジェクトが404で見れないー。
もしかしたら、俺の招待が必要？
[参考リンク](https://mocotan.hatenablog.com/entry/2022/04/06/021801)

@YU01BLC

**Comment by YU01BLC** [comment]
@kynmh69 
おっと、、
いまinviteしてみたから再度確認してみて〜

**Comment by kynmh69** [comment]
@YU01BLC 
招待ありがとー
見られたからクローズするわ
